esphome:
  name: warmtepomp-kleppen
  friendly_name: warmtepomp-kleppen

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2s6SGaFjJE656En6qxDv0ieWdMhZm+woor6dP2oD8Sg="

ota:
  - platform: esphome
    password: "c3d2df4acf58f52836fbfb2aeb784869"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Warmtepomp-Kleppen"
    password: "0guWFtixWXCO"

captive_portal:
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

pcf8574:
  - id: 'pcf8575_hub'
    address: 0x27
    pcf8575: true
switch:
  - platform: gpio
    name: "PCF8575 Pin #0"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #1"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 1
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #2"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 2
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #3"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 3
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #4"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #5"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 5
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #6"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0 interlock aan/uit relais
      number: 6
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #7"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0  interlock open/closed relais
      number: 7
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #8"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 8
      # One of INPUT or OUTPUT cloded
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "PCF8575 Pin #9"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 9
      # One of INPUT or OUTPUT cloded
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "PCF8575 Pin #10"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 10
      # One of INPUT or OUTPUT cloded
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "PCF8575 Pin #11"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 11
      # One of INPUT or OUTPUT cloded
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "PCF8575 Pin #12"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 12
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #13"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 13
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #14"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 14
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "PCF8575 Pin #15"
    pin:
      pcf8574: pcf8575_hub
      # Use pin number 0
      number: 15
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    update_interval: 15s